In [1]:
from pathlib import Path

import polars as pl

data_dir = Path.cwd().parent.parent.parent / "data"

raw_csv_path = data_dir / "bbbenji" / "bbbenji.csv"

df = pl.read_csv(raw_csv_path)

In [2]:
df.head()

shape: (5, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sentence  ┆ url       ┆ fileName  ┆ commonVoi ┆ … ┆ date      ┆ numberOfC ┆ numberOfS ┆ approxim │
│ ---       ┆ ---       ┆ ---       ┆ ceFileNam ┆   ┆ ---       ┆ lipsWithS ┆ kipsForSe ┆ ateDurat │
│ str       ┆ str       ┆ str       ┆ e         ┆   ┆ str       ┆ entence   ┆ ntence    ┆ ion      │
│           ┆           ┆           ┆ ---       ┆   ┆           ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆ i64       ┆ i64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ The       ┆ https://s ┆ 64113e55b ┆ common_vo ┆ … ┆ Tue Mar   ┆ 2         ┆ 0         ┆ 5.681    │
│ steady    ┆ sr-data.s ┆ f594264a9 ┆ ice_en_62 ┆   ┆ 14 2023   ┆           ┆           ┆          │
│ drip is   ┆ 3.amazona ┆ 944162.wa ┆ 8542.mp3  ┆   ┆ 23:41:10  ┆           ┆           ┆          │
│ worse     ┆ ws.…      ┆ v         ┆           ┆   ┆ GMT-0…    ┆           ┆           ┆          │
│ than …    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Benjamin  ┆ https://s ┆ 64113e55b ┆ common_vo ┆ … ┆ Tue Mar   ┆ 2         ┆ 0         ┆ 9.154    │
│ climbed   ┆ sr-data.s ┆ f594264a9 ┆ ice_en_20 ┆   ┆ 14 2023   ┆           ┆           ┆          │
│ over the  ┆ 3.amazona ┆ 944163.wa ┆ 836598.mp ┆   ┆ 23:41:10  ┆           ┆           ┆          │
│ wall…     ┆ ws.…      ┆ v         ┆ 3         ┆   ┆ GMT-0…    ┆           ┆           ┆          │
│ The manuf ┆ https://s ┆ 64113e55b ┆ common_vo ┆ … ┆ Tue Mar   ┆ 2         ┆ 0         ┆ 8.43     │
│ acturer   ┆ sr-data.s ┆ f594264a9 ┆ ice_en_26 ┆   ┆ 14 2023   ┆           ┆           ┆          │
│ of the    ┆ 3.amazona ┆ 944164.wa ┆ 944671.mp ┆   ┆ 23:41:10  ┆           ┆           ┆          │
│ discs …   ┆ ws.…      ┆ v         ┆ 3         ┆   ┆ GMT-0…    ┆           ┆           ┆          │
│ The       ┆ https://s ┆ 64113e55b ┆ common_vo ┆ … ┆ Tue Mar   ┆ 2         ┆ 0         ┆ 10.092   │
│ riding is ┆ sr-data.s ┆ f594264a9 ┆ ice_en_19 ┆   ┆ 14 2023   ┆           ┆           ┆          │
│ located   ┆ 3.amazona ┆ 944165.wa ┆ 987509.mp ┆   ┆ 23:41:10  ┆           ┆           ┆          │
│ in the s… ┆ ws.…      ┆ v         ┆ 3         ┆   ┆ GMT-0…    ┆           ┆           ┆          │
│ There was ┆ https://s ┆ 64113e55b ┆ common_vo ┆ … ┆ Tue Mar   ┆ 2         ┆ 0         ┆ 12.901   │
│ an        ┆ sr-data.s ┆ f594264a9 ┆ ice_en_31 ┆   ┆ 14 2023   ┆           ┆           ┆          │
│ accident  ┆ 3.amazona ┆ 944161.wa ┆ 5251.mp3  ┆   ┆ 23:41:10  ┆           ┆           ┆          │
│ at work,… ┆ ws.…      ┆ v         ┆           ┆   ┆ GMT-0…    ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
# save as parquet

parquet_path = data_dir / "bbbenji" / "bbbenji.parquet"

df.write_parquet(parquet_path)

In [4]:
# Check the schema to see available columns
df.schema

Schema([('sentence', String),
        ('url', String),
        ('fileName', String),
        ('commonVoiceFileName', String),
        ('speechPatterns', String),
        ('userId', String),
        ('sentenceId', String),
        ('date', String),
        ('numberOfClipsWithSentence', Int64),
        ('numberOfSkipsForSentence', Int64),
        ('approximateDuration', Float64)])

In [7]:
# Load the parquet file and prepare for async downloads
import asyncio
from pathlib import Path
from urllib.parse import urlparse

import aiofiles
import aiohttp

# Read the parquet file
df = pl.read_parquet(data_dir / "bbbenji" / "bbbenji.parquet")

# Set up the audio directory
audio_dir = Path(data_dir / "bbbenji" / "audio")
audio_dir.mkdir(parents=True, exist_ok=True)

# Extract URLs using Polars' built-in features
urls = df["url"].to_list()

print(f"Found {len(urls)} URLs to download")

Found 2334 URLs to download

In [8]:
async def download_file(session: aiohttp.ClientSession, url: str, save_path: Path) -> bool:
    """Download a file from URL and save it to the specified path"""
    try:
        async with session.get(url) as response:
            if response.status == 200:
                async with aiofiles.open(save_path, "wb") as f:
                    await f.write(await response.read())
                return True
            else:
                print(f"Failed to download {url}: Status {response.status}")
                return False
    except Exception as e:
        print(f"Error downloading {url}: {e}")
        return False


async def download_all_files(urls: list[str], output_dir: Path, max_concurrent: int = 10):
    """Download all files asynchronously with concurrency control"""
    from tqdm.asyncio import tqdm as async_tqdm

    async with aiohttp.ClientSession() as session:
        semaphore = asyncio.Semaphore(max_concurrent)
        pbar = async_tqdm(total=len(urls), desc="Downloading files")

        async def download_with_semaphore(url: str):
            async with semaphore:
                # Extract filename from URL
                parsed_url = urlparse(url)
                filename = Path(parsed_url.path).name

                # If no filename in URL, generate one from the URL hash
                if not filename or filename == "/":
                    import hashlib

                    filename = hashlib.md5(url.encode()).hexdigest() + ".mp3"

                save_path = output_dir / filename

                # Skip if file already exists
                if save_path.exists():
                    pbar.set_postfix_str(f"Skipped: {filename[:30]}...")
                    pbar.update(1)
                    return True

                success = await download_file(session, url, save_path)
                if success:
                    pbar.set_postfix_str(f"Downloaded: {filename[:30]}...")
                else:
                    pbar.set_postfix_str(f"Failed: {filename[:30]}...")
                pbar.update(1)
                return success

        # Create tasks for all downloads
        tasks = [download_with_semaphore(url) for url in urls]

        # Execute all downloads concurrently
        results = await asyncio.gather(*tasks, return_exceptions=True)

        pbar.close()

        successful = sum(1 for r in results if r is True)
        failed = len(results) - successful

        print(f"\nDownload complete: {successful} successful, {failed} failed")
        return results

In [9]:
# Run the async downloads
# Use await directly since Jupyter notebooks support top-level await
results = await download_all_files(urls, audio_dir, max_concurrent=10)

Downloading files: 100%|██████████| 2334/2334 [01:46<00:00, 21.87it/s, Downloaded: 6412ba078a3197d8284889f9.wav...]

Download complete: 2334 successful, 0 failed

In [ ]:
# adjust file paths to be relative to the current working directory
audio_dir_relative = "data/bbbenji/audio/"
df = df.with_columns(
    pl.concat_str([pl.lit(audio_dir_relative), pl.col("url").str.split("/").list.last()]).alias(
        "audio_path"
    )
)

# save the dataframe to a parquet file
df.write_parquet(data_dir / "bbbenji" / "bbbenji.parquet")

# read the parquet file
df = pl.read_parquet(data_dir / "bbbenji" / "bbbenji.parquet")
df.head()

shape: (5, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sentence  ┆ url       ┆ fileName  ┆ commonVoi ┆ … ┆ numberOfC ┆ numberOfS ┆ approxima ┆ audio_pa │
│ ---       ┆ ---       ┆ ---       ┆ ceFileNam ┆   ┆ lipsWithS ┆ kipsForSe ┆ teDuratio ┆ th       │
│ str       ┆ str       ┆ str       ┆ e         ┆   ┆ entence   ┆ ntence    ┆ n         ┆ ---      │
│           ┆           ┆           ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str      │
│           ┆           ┆           ┆ str       ┆   ┆ i64       ┆ i64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ The       ┆ https://s ┆ 64113e55b ┆ common_vo ┆ … ┆ 2         ┆ 0         ┆ 5.681     ┆ data/bbb │
│ steady    ┆ sr-data.s ┆ f594264a9 ┆ ice_en_62 ┆   ┆           ┆           ┆           ┆ enji/aud │
│ drip is   ┆ 3.amazona ┆ 944162.wa ┆ 8542.mp3  ┆   ┆           ┆           ┆           ┆ io/64113 │
│ worse     ┆ ws.…      ┆ v         ┆           ┆   ┆           ┆           ┆           ┆ e55bf5…  │
│ than …    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Benjamin  ┆ https://s ┆ 64113e55b ┆ common_vo ┆ … ┆ 2         ┆ 0         ┆ 9.154     ┆ data/bbb │
│ climbed   ┆ sr-data.s ┆ f594264a9 ┆ ice_en_20 ┆   ┆           ┆           ┆           ┆ enji/aud │
│ over the  ┆ 3.amazona ┆ 944163.wa ┆ 836598.mp ┆   ┆           ┆           ┆           ┆ io/64113 │
│ wall…     ┆ ws.…      ┆ v         ┆ 3         ┆   ┆           ┆           ┆           ┆ e55bf5…  │
│ The manuf ┆ https://s ┆ 64113e55b ┆ common_vo ┆ … ┆ 2         ┆ 0         ┆ 8.43      ┆ data/bbb │
│ acturer   ┆ sr-data.s ┆ f594264a9 ┆ ice_en_26 ┆   ┆           ┆           ┆           ┆ enji/aud │
│ of the    ┆ 3.amazona ┆ 944164.wa ┆ 944671.mp ┆   ┆           ┆           ┆           ┆ io/64113 │
│ discs …   ┆ ws.…      ┆ v         ┆ 3         ┆   ┆           ┆           ┆           ┆ e55bf5…  │
│ The       ┆ https://s ┆ 64113e55b ┆ common_vo ┆ … ┆ 2         ┆ 0         ┆ 10.092    ┆ data/bbb │
│ riding is ┆ sr-data.s ┆ f594264a9 ┆ ice_en_19 ┆   ┆           ┆           ┆           ┆ enji/aud │
│ located   ┆ 3.amazona ┆ 944165.wa ┆ 987509.mp ┆   ┆           ┆           ┆           ┆ io/64113 │
│ in the s… ┆ ws.…      ┆ v         ┆ 3         ┆   ┆           ┆           ┆           ┆ e55bf5…  │
│ There was ┆ https://s ┆ 64113e55b ┆ common_vo ┆ … ┆ 2         ┆ 0         ┆ 12.901    ┆ data/bbb │
│ an        ┆ sr-data.s ┆ f594264a9 ┆ ice_en_31 ┆   ┆           ┆           ┆           ┆ enji/aud │
│ accident  ┆ 3.amazona ┆ 944161.wa ┆ 5251.mp3  ┆   ┆           ┆           ┆           ┆ io/64113 │
│ at work,… ┆ ws.…      ┆ v         ┆           ┆   ┆           ┆           ┆           ┆ e55bf5…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘